services:
  - type: web
    name: mplads-risk-intelligence
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: API_URL
        value: http://127.0.0.1:8000
      - key: PYTHON_VERSION
        value: 3.10.12
